# cmd: "docker-compose --project-name epitech_workshop -f docker-compose.yml up"
# /!\ WARNING /!\
#   * Username: root
#   * Password: root
version: '3.1'

services:

  db:
    image: mariadb
    container_name: epitech_mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    networks:
      - workshop

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: epitech_phpmyadmin
    restart: always
    environment:
      PMA_ARBITRARY: 0
      PMA_HOST: db
    ports:
      - "8080:80"
    links:
      - db
    depends_on:
      - db
    networks:
      - workshop

networks:
  workshop:
    driver: bridge
